using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExistenciaMongoDb.Model
{
    public class Existencia
    {
        public string Code { get; set; }
        public string ProductName { get; set; }
        public decimal CEDISSTGO { get; set; }
        public int CEDISSTGOMax { get; set; }
        public decimal SFMCENTRO { get; set; }
        public int SFMCENTROMax { get; set; }
        public decimal SFMColonial { get; set; }
        public int SFMColonialMax { get; set; }
        public decimal GUIZA { get; set; }
        public int GUIZAMax { get; set; }
        public decimal MOCA { get; set; }
        public int MOCAMax { get; set; }
        public decimal MAO { get; set; }
        public int MAOMax { get; set; }
        public decimal LaMoraleja { get; set; }
        public int LaMoralejaMax { get; set; }
        public decimal RafaelVidal { get; set; }
        public int RafaelVidalMax { get; set; }
        public decimal AntonioGuzman { get; set; }
        public int AntonioGuzmanMax { get; set; }
        public decimal GURABO { get; set; }
        public int GURABOMax { get; set; }
        public decimal VillaOlimpica { get; set; }
        public int VillaOlimpicaMax { get; set; }
        public decimal EnsanchezLibertad { get; set; }
        public int EnsanchezLibertadMax { get; set; }
        public decimal CristoRey { get; set; }
        public int CristoReyMax { get; set; }
        public decimal LasAmericas { get; set; }
        public int LasAmericasMax { get; set; }
        public decimal TAMBORIL { get; set; }
        public int TAMBORILMax { get; set; }
        public decimal RepublicaDeArgentina { get; set; }
        public int RepublicaDeArgentinaMax { get; set; }
        public decimal Restauracion { get; set; }
        public int RestauracionMax { get; set; }
        public decimal JardinesMetropolitanos { get; set; }
        public int JardinesMetropolitanosMax { get; set; }
        public decimal RAFAELVIDAL2 { get; set; }
        public int RAFAELVIDAL2Max { get; set; }
        public decimal LosLaureles { get; set; }
        public int LosLaurelesMax { get; set; }
        public decimal Trinitaria { get; set; }
        public int TrinitariaMax { get; set; }
        public decimal Guazumal { get; set; }
        public int GuazumalMax { get; set; }
        public decimal BravoPontezuela { get; set; }
        public int BravoPontezuelaMax { get; set; }
        public decimal Esperanza { get; set; }
        public int EsperanzaMax { get; set; }
        public decimal ELVERGEL { get; set; }
        public int ELVERGELMax { get; set; }
        public decimal METROJPD { get; set; }
        public int METROJPDMax { get; set; }
        public decimal MARIAMONTES { get; set; }
        public int MARIAMONTESMax { get; set; }
        public decimal PIANTINI { get; set; }
        public int PIANTINIMax { get; set; }
        public decimal MIRADORNORTE1 { get; set; }
        public int MIRADORNORTE1Max { get; set; }
        public decimal MILLON1 { get; set; }
        public int MILLON1Max { get; set; }
        public decimal RENACIMIENTO1 { get; set; }
        public int RENACIMIENTO1Max { get; set; }
        public decimal MIRADORNORTE2 { get; set; }
        public int MIRADORNORTE2Max { get; set; }
        public decimal PARQUEINDEPENDENCIA { get; set; }
        public int PARQUEINDEPENDENCIAMax { get; set; }
        public decimal TIRADENTES { get; set; }
        public int TIRADENTESMax { get; set; }
        public decimal RENACIMIENTO2 { get; set; }
        public int RENACIMIENTO2Max { get; set; }
        public decimal TREINTADEMAYO { get; set; }
        public int TREINTADEMAYOMax { get; set; }
        public decimal RENACIMIENTO3 { get; set; }
        public int RENACIMIENTO3Max { get; set; }
        public decimal LOTERIADN { get; set; }
        public int LOTERIADNMax { get; set; }
        public decimal NACO { get; set; }
        public int NACOMax { get; set; }
        public decimal BARRIODUARTE { get; set; }
        public int BARRIODUARTEMax { get; set; }
        public decimal BUENOSAIRESHERRERA { get; set; }
        public int BUENOSAIRESHERRERAMax { get; set; }
        public decimal LASPALMAS { get; set; }
        public int LASPALMASMax { get; set; }
        public decimal VILLACARMEN { get; set; }
        public int VILLACARMENMax { get; set; }
        public decimal ELBRISAL { get; set; }
        public int ELBRISALMax { get; set; }
        public decimal LOSCORALES { get; set; }
        public int LOSCORALESMax { get; set; }
        public decimal ALMAROSA1 { get; set; }
        public int ALMAROSA1Max { get; set; }
        public decimal REPUBLICADECOLOMBIA { get; set; }
        public int REPUBLICADECOLOMBIAMax { get; set; }
        public decimal ZONAINDUSTRIAL { get; set; }
        public int ZONAINDUSTRIALMax { get; set; }
        public decimal AVVENEZUELA { get; set; }
        public int AVVENEZUELAMax { get; set; }
        public decimal VILLAFARO { get; set; }
        public int VILLAFAROMax { get; set; }
        public decimal SANISIDRO { get; set; }
        public int SANISIDROMax { get; set; }
        public decimal CANCINO { get; set; }
        public int CANCINOMax { get; set; }
        public decimal CEDISSDQ { get; set; }
        public int CEDISSDQMax { get; set; }
        public decimal MILLON2 { get; set; }
        public int MILLON2Max { get; set; }
        public decimal ENSANCHEZLIBERTAD { get; set; }
        public int ENSANCHEZLIBERTADMax { get; set; }
        public decimal BELLAVISTA { get; set; }
        public int BELLAVISTAMax { get; set; }
        public decimal VILLAMELLA { get; set; }
        public int VILLAMELLAMax { get; set; }
        public decimal JULIETAMORALES { get; set; }
        public int JULIETAMORALESMax { get; set; }
    }
}
